new muffled effect
mmattDonk/AI-TTS-Donations pull request #133
Opened 2022-02-27 00:16 UTC by mopoIo

2022-02-27 04:39 UTC, mmattbtw requested changes
can you make it a bit louder? add a gain filter because it's too quiet atm

2022-02-27 06:25 UTC, mopoIo commented
it should be good now, let me know your thoughts

2022-02-27 06:37 UTC, mmattbtw approved these changes
LGTM!

2022-02-27 06:37 UTC, merged

2022-06-10 19:24 UTC, mmattbtw commented
@all-contributors add @mopoIo for audio